---
- name: Set up Attacker VM with GUI, GoPhish, VPN, DB tools
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install XFCE and LightDM
      apt:
        name:
          - xfce4
          - xfce4-goodies
          - lightdm
        state: present

    - name: Set LightDM as default display manager
      debconf:
        name: lightdm
        question: shared/default-x-display-manager
        value: lightdm
        vtype: select

    - name: Enable LightDM to start at boot
      systemd:
        name: lightdm
        enabled: yes

    - name: Install browser (Firefox)
      apt:
        name: firefox
        state: present

    - name: Install GoLang and Git
      apt:
        name:
          - golang
          - git
        state: present

    - name: Clone GoPhish from GitHub
      git:
        repo: https://github.com/gophish/gophish.git
        dest: /opt/gophish

    - name: Build GoPhish
      shell: |
        cd /opt/gophish
        go build
      args:
        creates: /opt/gophish/gophish

    - name: Install DB Browser for SQLite and CLI
      apt:
        name:
          - sqlitebrowser
          - sqlite3
        state: present

    - name: Install OpenVPN
      apt:
        name: openvpn
        state: present

    - name: Move client.ovpn to OpenVPN config
      copy:
        src: /home/vagrant/client.ovpn
        dest: /etc/openvpn/client.conf
        remote_src: yes

    - name: Enable OpenVPN client on boot
      shell: |
        echo "[Unit]
        Description=OpenVPN client
        After=network.target

        [Service]
        ExecStart=/usr/sbin/openvpn --config /etc/openvpn/client.conf
        Restart=always

        [Install]
        WantedBy=multi-user.target" > /etc/systemd/system/openvpn-client.service
      args:
        creates: /etc/systemd/system/openvpn-client.service

    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn-client
        enabled: yes
        state: started

    - name: Reboot the machine
      reboot:
        msg: "Rebooting after full attacker-vm setup"
        reboot_timeout: 600
