version: '3.8'

services:
  axigen:
    image: axigen/axigen:latest
    container_name: mailserver
    restart: unless-stopped
    ports:
      - "25:25"       # SMTP
      - "465:465"     # SMTPS
      - "587:587"     # SMTP with Auth
      - "110:110"     # POP3
      - "995:995"     # POP3S
      - "143:143"     # IMAP
      - "993:993"     # IMAPS
      - "80:80"       # WebMail (HTTP)
      - "443:443"     # WebMail (HTTPS)
      - "9443:9443"   # WebAdmin
    volumes:
      - axigen-data:/var/opt/axigen

    environment:
      - AXIGEN_ACCEPT_LICENSE=YES
      - AXIGEN_ADMIN_PASSWORD=admin123

volumes:
  axigen-data:

