version: '3'

services:
  gophish:
    image: gophish/gophish
    container_name: gophish
    ports:
      - "3333:3333"  # Admin panel
      - "80:80"      # Phishing site
    volumes:
      - gophish_data:/opt/gophish

volumes:
  gophish_data:
