---
- name: Set up Axigen Mail Server and OpenVPN
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - git
          - openvpn
        state: present

    - name: Download Axigen .deb package
      get_url:
        url: https://www.axigen.com/mail-server/download/deb/latest/axigen_10.6.14-1_amd64.deb
        dest: /tmp/axigen.deb
        validate_certs: yes

    - name: Install Axigen package
      apt:
        deb: /tmp/axigen.deb

    - name: Enable and start Axigen service
      systemd:
        name: axigen
        enabled: yes
        state: started

    - name: Remove any existing Easy-RSA content
      file:
        path: /etc/openvpn/easy-rsa
        state: absent

    - name: Clone Easy-RSA repo
      git:
        repo: https://github.com/OpenVPN/easy-rsa.git
        dest: /etc/openvpn/easy-rsa
        version: v3.1.6

    - name: Set Easy-RSA script path as executable
      file:
        path: /etc/openvpn/easy-rsa/easyrsa3/easyrsa
        mode: '0755'
        state: file


    - name: Initialize PKI
      command: ./easyrsa init-pki
      args:
        chdir: /etc/openvpn/easy-rsa/easyrsa3

    - name: Build CA (non-interactive)
      command: ./easyrsa --batch build-ca nopass
      args:
        chdir: /etc/openvpn/easy-rsa/easyrsa3

    - name: Generate DH params
      command: ./easyrsa gen-dh
      args:
        chdir: /etc/openvpn/easy-rsa/easyrsa3

    - name: Generate server certificate and key
      command: ./easyrsa --batch build-server-full server nopass
      args:
        chdir: /etc/openvpn/easy-rsa/easyrsa3


    - name: Generate client certificate and key
      command: ./easyrsa --batch build-client-full client_vm nopass
      args:
        chdir: /etc/openvpn/easy-rsa/easyrsa3

    - name: Copy server keys and certs to OpenVPN
      copy:
        src: "/etc/openvpn/easy-rsa/easyrsa3/pki/{{ item }}"
        dest: "/etc/openvpn/{{ item | basename }}"
        remote_src: yes
      loop:
        - ca.crt
        - issued/server.crt
        - private/server.key
        - dh.pem

    - name: Create OpenVPN server config
      copy:
        dest: /etc/openvpn/server.conf
        content: |
          port 1194
          proto udp
          dev tun
          ca ca.crt
          cert server.crt
          key server.key
          dh dh.pem
          topology subnet
          server 10.8.0.0 255.255.255.0
          ifconfig-pool-persist ipp.txt
          keepalive 10 120
          cipher AES-256-CBC
          user nobody
          group nogroup
          persist-key
          persist-tun
          status openvpn-status.log
          verb 3

    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn@server
        enabled: yes
        state: started

    - name: Read CA cert
      slurp:
        src: /etc/openvpn/easy-rsa/easyrsa3/pki/ca.crt
      register: ca_cert

    - name: Read client cert
      slurp:
        src: /etc/openvpn/easy-rsa/easyrsa3/pki/issued/client_vm.crt
      register: client_cert

    - name: Read client key
      slurp:
        src: /etc/openvpn/easy-rsa/easyrsa3/pki/private/client_vm.key
      register: client_key

    - name: Generate .ovpn client config
      copy:
        dest: /vagrant/client.ovpn
        content: |
          client
          dev tun
          proto udp
          remote 192.168.56.20 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          auth SHA256
          comp-lzo
          verb 3
          <ca>
          {{ ca_cert.content | b64decode }}
          </ca>
          <cert>
          {{ client_cert.content | b64decode }}
          </cert>
          <key>
          {{ client_key.content | b64decode }}
          </key>

    ## ---------------------------
    ## BUDGIE DESKTOP SECTION
    ## ---------------------------

    - name: Install Budgie desktop environment
      apt:
        name:
          - ubuntu-budgie-desktop
          - lightdm
        state: present

    - name: Set LightDM as default display manager
      debconf:
        name: lightdm
        question: shared/default-x-display-manager
        value: lightdm
        vtype: select

    - name: Ensure graphical target is set
      systemd:
        name: graphical.target
        enabled: yes